ESGVOC_ROOT_LOGGER_NAME = 'esgvoc'
LOG_LEVEL = 'INFO'
API_WEB_DOCUMENTATION_URL_PREFIX = 'https://esgf.github.io/esgf-vocab/api_documentation'
API_VERSION = 'v1'
API_PREFIX = f'/api/{API_VERSION}'
URI_PREFIX = '/resource'
SWAGGER_URL = f'{API_PREFIX}/docs'
OPEN_API_URL = f'{API_PREFIX}/openapi.json'

# Prefix for the API Web documentation of the route.
UNIVERSE_PAGE_PREFIX = 'universe.html#esgvoc.api.universe'
PROJECTS_PAGE_PREFIX = 'projects.html#esgvoc.api.projects'
DRS_GEN_PREFIX = 'drs.html#esgvoc.apps.drs.generator.DrsGenerator'
DRS_VAL_PREFIX = 'drs.html#esgvoc.apps.drs.validator.DrsValidator'
JSG_PREFIX = 'jsg.html#esgvoc.apps.jsg.json_schema_generator'
