name: esgvoc-backend

services:
    latest:
        image: ghcr.io/espri-mod/esgf-vocab-backend
        ports:
            - 80:9999
        environment:
            - WEB_CONCURRENCY=7
        restart: always
        secrets:
            - gh_web_hook_secret
        volumes:
            - type: bind
              source: update
              target: /var/www/esgvoc-backend/update

    test:
        extends: latest
        image: esgvoc-backend:test
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1
        build: .
        restart: no
        secrets:
            - gh_web_hook_secret
        volumes:
            - type: bind
              source: update_test
              target: /var/www/esgvoc-backend/update

secrets:
  gh_web_hook_secret:
    file: ./gh_web_hook_secret
