name: esgvoc-backend

services:
    prod:
        image: ghcr.io/espri-mod/esgf-vocab-backend
        container_name: prod
        ports:
            - 80:9999
        environment:
            - WEB_CONCURRENCY=7
        restart: always
        secrets:
            - gh_web_hook_secret
        volumes:
            - type: bind
              source: update
              target: /var/www/esgvoc-backend/update

    deploy:
        extends: prod
        image: esgvoc-backend:deploy
        container_name: deploy
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1
        build: .

    update:
        extends: prod
        container_name: update
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1

secrets:
  gh_web_hook_secret:
    file: ./gh_web_hook_secret
