name: esgvoc-backend

services:
    prod:
        image: ghcr.io/espri-mod/esgf-vocab-backend
        container_name: prod
        user: "${UID-1000}:${GID-1000}"
        ports:
            - 80:9999
        environment:
            - WEB_CONCURRENCY=7
        restart: always
        secrets:
            - gh_web_hook_secret
        volumes:
            - type: bind
              source: update
              target: /home/docker/esgvoc-backend/update

    deploy:
        extends: prod
        image: esgvoc-backend:deploy
        container_name: deploy
        user: "${UID-1000}:${GID-1000}"
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1
        build:
            context: "."

    update:
        extends: prod
        container_name: update
        user: "${UID-1000}:${GID-1000}"
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1

secrets:
  gh_web_hook_secret:
    file: ./gh_web_hook_secret
