name: esgvoc-backend

services:
    latest:
        image: ghcr.io/espri-mod/esgf-vocab-backend
        ports:
            - 80:9999
        environment:
            - WEB_CONCURRENCY=7
        restart: always

    test:
        extends: latest
        image: esgvoc-backend:test
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1
        build: .
        restart: no
