name: esgvoc-backend

services:
    prod:
        image: ghcr.io/espri-mod/esgf-vocab-backend
        container_name: prod
        user: "2000:2000"
        ports:
            - 80:9999
        environment:
            - WEB_CONCURRENCY=7
            - GH_WEB_HOOK_SECRET_FILE="/run/secrets/gh_web_hook_secret"
        secrets:
            - gh_web_hook_secret
        volumes:
            - type: bind
              source: update
              target: /home/docker/esgvoc-backend/deployment/update
        restart: always

    deploy:
        extends: prod
        image: esgvoc-backend:deploy
        container_name: deploy
        user: "2000:2000"
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1
        build:
            context: "."
        restart: no

    update:
        extends: prod
        container_name: update
        user: "2000:2000"
        ports: !override
            - 8080:9999
        environment: !override
            - WEB_CONCURRENCY=1
        restart: no

secrets:
  gh_web_hook_secret:
    environment: GH_WEBHOOK_SECRET
