name: esgvoc-backend

services:
    prod:
        image: ghcr.io/espri-mod/esgf-vocab-backend
        container_name: prod
        user: "2000:2000"
        environment:
            - GUNICORN_CMD_ARGS=--workers=5 --bind=0.0.0.0:80 --timeout=10
            - GH_WEB_HOOK_SECRET_FILE=/run/secrets/gh_web_hook_secret
        secrets:
            - gh_web_hook_secret
        volumes:
            - type: bind
              source: update
              target: /home/docker/esgvoc-backend/deployment/update
        restart: always

    deploy:
        extends: prod
        image: esgvoc-backend:deploy
        container_name: deploy
        user: "2000:2000"
        environment: !override
            - GUNICORN_CMD_ARGS=--workers=1 --bind=0.0.0.0:8080 --timeout=10
        build:
            context: "."
        restart: no

    update:
        extends: prod
        container_name: update
        user: "2000:2000"
        environment: !override
            - GUNICORN_CMD_ARGS=--workers=1 --bind=0.0.0.0:8080 --timeout=10
        restart: no

secrets:
  gh_web_hook_secret:
    environment: GH_WEB_HOOK_SECRET
