name: Pull request test

on:
  pull_request:
    branches:
      - main

jobs:
  pr_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rye install
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Rye sync
        run: rye sync

      - name: ESGVOC install
        run: rye run esgvoc install

      - name: Test
        run: rye run pytest tests
