name: Unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync
        run: uv sync

      - name: ESGVOC install
        run: uv run esgvoc install

      - name: Test
        run: uv run pytest tests
