name: Unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync
        run: uv sync

      - name: ESGVOC install
        run: |
          uv run esgvoc use universe@latest
          uv run esgvoc use cmip6@latest
          uv run esgvoc use cmip6plus@latest
          uv run esgvoc use cmip7@latest
          uv run esgvoc use cordex-cmip5@latest
          uv run esgvoc use cordex-cmip6@latest
          uv run esgvoc use emd@latest
          uv run esgvoc use input4mips@latest
          uv run esgvoc use obs4ref@latest

      - name: Test
        run: uv run pytest tests
